---
name: sample architecture
decoders:
  - name: decoder_a
    type: null
    size: null
    output_dest: null
encoders:
  - name: encoder_a
    type: image
    length: null
    width: null
    num_channels: null
    input_source: null
    outputs: [vis_a]
problem_domains:
  - name: vis_a
    type: cortical
    size: null
    outputs: [vis_b,vis_c]
  - name: vis_b
    type: cortical
    size: null
    outputs: [comb_a]
  - name: vis_c
    type: cortical
    size: null
    outputs: [comb_a]
  - name: comb_a
    type: cortical
    size: null
    outputs: [decoder_a]
edges:
  - encoder_a:vis_a
  - vis_a:vis_b
  - vis_a:vis_c
  - vis_b:comb_a
  - vis_c:comb_a
  - comb_a:decoder_a
...