---
Module or Part Name: Direct-to-Core Shell Input Bypass
Layers: Coder
Cell Details: Dedicated Functions that can act as Nodes. They are not acting as cells though
Purpose: To serve as a placeholder for input that would otherwise be extracted by the Shell Input Pipelines. A way to send strings directly to the higher-level semantic structure Expounders without need for another form of shell
Pipeline: Input
Input Melds: N
Input Semantic Field Sizes (Key:Shape): N
Internal Melds (wht bt fld mpngs?): N
Output Melds: A->Gate[Expounder]
A->Output Likelihood Modulator
A-> Reward Availability Detector
Output Semantic Field Sizes: InputA:(8+1+8+1) 8-Pod Characters
Circuits it Defines: DirectInput
Misc Circuits it uses: N
Input Circuits: Input Meld
Output Circuits: Output Meld
Channels: 1
...