---
Module or Part Name: DM
Layers: ACLL
Cell Details: Typical ACLL Node Distributions
Purpose: All the DM pieces (PDM, Claus, BG) together try to minimize dopamine usage in order to keep it around for as long as possible
It's unclear if the BG, and other Subcort correspondents of the DM have their own channels or not. (Note: I suspect that corresponds most closely with some combination of the PFC, and Cingulate)

The gateway region for the DM relays inputs from the amygdala and olfactory cortex and projects to itself and the limbic system and in turn relays them to the prefrontal association cortex (parts of the DM pipeline that are being excluded for now).
If Dopamine consumption is required to make decisions. The amount of dopamine available can be used to limit the number of cycles to some function of the amount of reward detected before forcing an output. Really large rewards would thus produce lots of effort before decision, small predicted rewards would thus produce low amounts of effort before decision.
Pipeline: DM/Review
Input Melds: * in DM circuit modules (Currently 9 modules with 5 of them having multiple containers. Containers may be removed and split into separate modules if found cumbersome) (Focus and Activity Ctrlr modules are not in the primary DM circuit, but they do pull from it's list)
Reward Attempts Circuit (overlayed onto the others)
DM Activity Circuit (overlayed onto the others except for the channel that corresponds to it)
Reward Activity Circuit (overlayed onto the others)
Input Semantic Field Sizes (Key:Shape): The combined size of this list of Pod Sizes:
CE,Ch,Tk,Ph,Com,Ch,Tk,Ph,Stg
which looks like
DomainA,InputA,16xOutputA-Ch,8xOutputA-Tk,4xOutputA-Ph,OuputA,OutputA
Internal Melds (wht bt fld mpngs?): Differs per Channel
Output Melds: Differs per Channel
Output Semantic Field Sizes: GlobalMashA: 1/dest_fract of each Synch Circuit modules total shape sans itself
Circuits it Defines: DM
Misc Circuits it uses: Active Release, Part B
Gate
Synch (Projects to all Synch channels with Defining Modules. Which should be all of them. This part of the synch circuit simple doesn't define a module)
(DM list is used to define the primary outputs of some DM based circuits, there are currently 9 modules that are part of the DM circuit)
Input Circuits: Differs per Channel
Output Circuits: Differs per Channel
Channels: num DP circuit melds
(=COUNTIF(L2:L114, "*DP*"))
...