---
Name: Expounder Controller (in gateway)
Layers: BCLL+
Cell Details: Typical BCLL+ Node Distributions
Purpose: Takes a statement, decomposes and recomposes it, and then relays it to the Concept Eval. Oftentimes, a good way to understand something is by ripping it apart and putting it back together again
Pipeline: Extraction
Input Melds:
  - DirectInput,AWhl
  - RewardAttempts,MeldId_ExpounderController
Internal Melds: BCCL+(InputA, [Destinations])
Output Melds: Energy,*
Output Shapes:
  OutFunAtms: np.array_split(16, InAWhl)
  OutFunTkns: np.array_split(8, InAWhl)
  OutFunPrts: np.array_split(4, InAWhl)
  OutFunWhl: Join(InAAtms) + Join(InATkns) + Join(InAPrts) + InAWhl

Circuits it Defines: Extraction
Misc Circuits it uses:
  - ActiveReleasePartA
  - DM
  - Gate
  - Synch
Channels:
  - 1 per Input Meld to it
  - Just D2CSIB for now
...
