name: golem
dependencies:
- hypothesis
- numpy
- pillow
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- pandas
- path.py
- pip
- cython
- pylint
- yaml