---
Name: Synchronizer
Layers: Custom
Cell Details: -----
Purpose: Serves to globally synchronize the Module states/waves (formerly CL) Also receives from the not incoroprated Maps, and Amygdala
Pipeline: Operations Control
Input Melds:
  Primary: all Synch segment defining Modules
  Modulation: synch segment overlaying modules
  RewardActivityModulator:
  RewardAvailabilityDetector:
Generated Shapes:
  Stuff: ?
Output Melds:
  All: Synch Circuit connected Modules data reciprocal for all but Active Release
  Hm: All Synch Circuit connected channels project to the Active Release Part A &| B that their corresponding Defining (creates a channel) Modules projec to
Output Semantic Field Sizes:
  SynchId_ReciprocalModule
  SynchId_ResponseOutputController
  SynchId_DMOutputController
Circuits it Defines: Synch
Links: ?
Channels: 1 per CL circuit
...