---
name: cortex
layers:
  - name: one
    point_size: 0
    cell_morphology: none
    destinations:
      - none
  - name: two
    point_size: 30
    cell_morphology:
      - pyramid
    destinations:
      - none
  - name: three
    point_size: 30
    cell_morphology:
      - pyramid
    destinations:
      - none
  - name: four
    point_size: 30
    cell_morphology:
      - pyramid
      - star
    destinations:
      - none
  - name: five
    point_size: 30
    cell_morphology:
      - pyramid
    destinations:
      - none
      - output
      - pair
      - [same, same]
  - name: six
    point_size: 30
    cell_morphology:
      - pyramid
    destinations:
      - none
...