---
layers:
  - name: reticular
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
    order: 0
  - name: cort_relay
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
    order: 1
  - name: relay_inhib
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
    order: 2
  - name: matrix
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
    order: 3
...