---
name: relay
layers:
  - name: reticular
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
  - name: cort_relay
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
  - name: relay_inhib
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
  - name: matrix
    point_size: 1
    cell_morphology:
      - none
    destinations:
      - none
...