---
Id: DCLEG
Name: Decision Controlled Logos Encapsulator Group
StageToGroupsDicts:
  CntxtCtrl: [CntxtDwnInhib]
  InitProc: [IPBiInhibCtrl,IPDownInhib,IPStgAdv]
  AddtProc: [APBiInhibCtrl,APDownInhib,APStgAdv]
  ProcCtrl: [CBiInhibCtrl,CDownInhib,CUpInhib,CStgAdv]
  OutProc: [OPBiInhibCtrl,OPDownInhib,OPStgAdv]
  CntxtProc: [COBiInhibCtrl,COUpInhib,COStgAdv]
ShapeToGroupsDicts:
  ModuleField: [CntxtDwnInhib,IPBiInhibCtrl,IPDownInhib,IPStgAdv,APBiInhibCtrl,APDownInhib,APStgAdv,CBiInhibCtrl,CDownInhib,CUpInhib,CStgAdv,OPBiInhibCtrl,OPDownInhib,OPStgAdv,COBiInhibCtrl,COUpInhib,COStgAdv]
InputHooks:
  - CntxtIn: []
OutputHooks:
  - CntxtOut: [COStgAdv]
InputMelds:
  CntxtDwnInhib: null
  IPBiInhibCtrl: null
  IPDownInhib: null
  IPStgAdv: null
  APBiInhibCtrl: null
  APDownInhib: null
  APStgAdv: null
  CBiInhibCtrl: null
  CDownInhib: null
  CUpInhib: null
  CStgAdv: null
  OPBiInhibCtrl: null
  OPDownInhib: null
  OPStgAdv: null
  COBiInhibCtrl: null
  COUpInhib: null
  COStgAdv: null
OutputMelds:
  CntxtDwnInhib: []
  IPBiInhibCtrl: []
  IPDownInhib: []
  IPStgAdv: []
  APBiInhibCtrl: []
  APDownInhib: []
  APStgAdv: []
  CBiInhibCtrl: []
  CDownInhib: []
  CUpInhib: []
  CStgAdv: []
  OPBiInhibCtrl: []
  OPDownInhib: []
  OPStgAdv: []
  COBiInhibCtrl: []
  COUpInhib: []
  COStgAdv: []
LinksDefined: null
LinksUsed:
  - G_i
...