---
Id: GLG
Name: Gateway Layer Groups
StageToGroupsDicts:
  - NoiseCtrl: [NoiseDwnInhib,NoiseAdjInhib]
  - CycleRelay: [CycleGateCtrl,CycleStgAdv]
  - CntxtRelay: [CntxtStgAdv,CntxtUpInhib]
  - Relay: [StgAdv]
ShapeToGroupsDicts:
  G_i: [NoiseDwnInhib,NoiseAdjInhib,CycleGateCtrl,CycleStgAdv,CntxtStgAdv,CntxtUpInhib]
  Gate_i: [Relay]
InputMelds:
  NoiseDwnInhib: [NoiseAdjInhib-Inhibitor,NoiseCtrl-Energy]
  NoiseAdjInhib: [NoiseCtrl-Energy]
  CycleGateCtrl: [CycleRelay-Energy,NoiseDwnInhib-Inhibitor]
  CycleStgAdv: [CycleRelay-Energy]
  CntxtStgAdv: [CntxtRelay-Energy]
  CntxtUpInhib: [CntxtRelay-Energy]
  Relay: null
OutputMelds:
  NoiseDwnInhib: [CntxtUpInhib-Inhbitor,CycleRelay-Inhibitor,CntxtRelay-Inhibitor]
  NoiseAdjInhib: [NoiseDwnInhib-Inhibitor]
  CycleGateCtrl: [CycleRelay-Inhibitor]
  CycleStgAdv: [CycleRelay-Energy,CntxtCtrl-Energy,ProcCtrl-Energy]
  CntxtStgAdv: [CntxtRelay-Energy,CntxtCtrl-Energy,ProcCtrl-Energy]
  CntxtUpInhib: [CntxtRelay-Inhibitor]
  Relay: null
HooksInTo:
  NoiseIn: [NoiseDwnInhib,NoiseAdjInhib]
  CycleIn: [CycleGateCtrl,CycleStgAdv]
  CntxtIn: [CntxtStgAdv,CntxtUpInhib]
  RelayIn: [Relay]
HooksOutOf:
    CycleOut: [CycleStgAdv]
    CntxtOut: [CntxtStgAdv]
    RelayOut: [Relay]
LinksDefined:
  - LinkId: G_i
    HooksRequired:
      - CntxtIn
      - CntxtOut
      - CycleIn
      - CycleOut
      - NoiseIn
      - NoiseOut
  - LinkId: Gate_i
    HooksRequired:
      - RelayIn
      - RelayOut
LinksUsed: null
...