---
Name: Expounder Controller (in gateway)
Layers: BCLL+
Cell Details: Typical BCLL+ Node Distributions
Purpose: Takes a statement, decomposes and recomposes it, and then relays it to the Concept Eval. Oftentimes, a good way to understand something is by ripping it apart and putting it back together again
Pipeline: Extraction
InputMelds:
  Links: 1 Energy shape per Extraction link to the expounder
  DirectInput: Energy,AWhl
  RewardAvailabilityDetector: RESOURCE,SynchId_ExpounderController
Generated Shapes:
  OutFunWhl: Energy,Join(InAAtms) + Join(InATkns) + Join(InAPrts) + InAWhl + PrevAWhl
  OutFunAtms: Energy,np.array_split(16, InAWhl)
  OutFunTkns: Energy,np.array_split(8, InAWhl)
  OutFunPrts: Energy,np.array_split(4, InAWhl)
OutputMelds:
  ConceptEvalController: OutFunWhl
Links:
  ResponseOutputController: OutFunWhl
  DM: OutFunWhl
  Gate: OutFunWhl
  Synch: OutFunWhl
Function: ?????
Links it defines: Extraction
Channels:
  - 1 per Input Meld to it
  - Just D2CSIB for now
...
